default: &defaults
  asset_host: <%= ENV['ASSET_HOST'] %>
  metriks_interval: <%= ENV['METRIKS_INTERVAL'] %>
  instagram:
    client_id: <%= ENV['INSTAGRAM_CLIENT_ID'] %>
    client_secret: <%= ENV['INSTAGRAM_SECRET'] %>
    access_token: <%= ENV['INSTAGRAM_TOKEN'] %>
  indextank:
    api_url: <%= ENV['INDEXTANK_API_URL'] %>
  mongodb:
    url: <%= ENV['MONGODB_URL'] %>
  expires:
    api_cache:    <%= 30 * 60 %>
    popular_page: <%= 30 * 60 %>
    popular_feed: <%= 60 * 60 %>
    user_feed:    <%= 2 * 60 * 60 %>
    user_json:    <%= 2 * 60 * 60 %>
    user_page:    <%= 60 * 60 %>
    search_page:  <%= 20 * 60 %>
    tag_page:     <%= 20 * 60 %>
  user_blacklist: "<%= ENV['INSTAGRAM_USER_BLACKLIST'] %>"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
